config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  mount SolidQueueDashboard::Engine, at: "/solid-queue"

  devise_for :users, path: "", path_names: { sign_up: "register", sign_in: "login", sign_out: "logout" }
  resources :users, only: [ :index, :show ]

  resources :characters do
    member do
      post :choose
    end
  end

  get "items", to: "items#index"

  root "home#show"

  get "map", to: "map#show"
  resources :locations, only: :show do
    resources :nodes, only: :show do
      resources :recipes, only: :show
    end
  end

  resources :messages, only: :create

  resources :guilds
  resources :guild_characters

  resource :equipment
  resources :actions
end

app/models/recipe.rb
class Recipe < FrozenRecord::Base
  def items
    attributes["items"].map do |data|
      item_id, quantity = data.values_at("id", "quantity")
      [ Item.find(item_id), quantity ]
    end
  end

  def materials
    attributes["materials"].map do |data|
      item_id, quantity = data.values_at("id", "quantity")
      [ Item.find(item_id), quantity ]
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[ show ]
  before_action :set_node, only: %i[ show ]
  before_action :set_location, only: %i[ show ]

  def show
  end

  private

  def set_recipe
    @recipe = Recipe.find(params.expect(:id))
  end

  def set_node
    @node = Node.find(params.expect(:node_id))
  end

  def set_location
    @location = Location.find(params.expect(:location_id))
  end
end

app/views/recipes/_recipe.html.erb
<section class="divide-y divide-neutral-700">
  <div class="divide-y divide-neutral-600">
    <div class="py-3.5 px-4 bg-neutral-950">
      <h2 class="font-semibold">Items</h2>
      <p class="text-sm text-neutral-100">The crafted items.</p>
    </div>
    <ul role="list" class="divide-y divide-neutral-800 overflow-hidden bg-neutral-900 shadow-sm ring-1 ring-neutral-900/5">
      <% recipe.items.each do |item, quantity| %>
        <li class="relative flex justify-between gap-x-6 px-4 py-3.5 hover:bg-neutral-800">
          <div class="flex min-w-0 gap-x-4">
            <div class="min-w-0 flex-auto">
              <p class="text-sm/6 font-semibold">
                <%= item.name %>
              </p>
              <p class="mt flex text-xs/5 text-neutral-200">
                <%= quantity %>
              </p>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="divide-y divide-neutral-600">
    <div class="py-3.5 px-4 bg-neutral-950">
      <h2 class="font-semibold">Materials</h2>
      <p class="text-sm text-neutral-100">The required items.</p>
    </div>
    <ul role="list" class="divide-y divide-neutral-800 overflow-hidden bg-neutral-900 shadow-sm ring-1 ring-neutral-900/5">
      <% recipe.materials.each do |item, quantity| %>
        <li class="relative flex justify-between gap-x-6 px-4 py-3.5 hover:bg-neutral-800">
          <div class="flex min-w-0 gap-x-4">
            <div class="min-w-0 flex-auto">
              <p class="text-sm/6 font-semibold">
                <%= item.name %>
              </p>
              <p class="mt flex text-xs/5 text-neutral-200">
                <%= quantity %>
              </p>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
  <%= form_with(model: Action.new, scope: "node_action") do |form| %>
    <%= form.hidden_field :location_id, value: location.id %>
    <%= form.hidden_field :node_id, value: node.id %>
    <%= form.hidden_field :recipe_id, value: recipe.id %>
    <%= form.submit "Start action" %>
  <% end %>
</section>

app/views/recipes/show.html.erb
<% content_for :title, @recipe.name %>

<%= turbo_frame_tag :map, autoscroll: true, data: { autoscroll_block: "start", autoscroll_behaviour: "smooth" } do %>
  <div class="bg-neutral-900 border-y sm:border border-neutral-600 divide-y divide-neutral-600 overflow-hidden sm:rounded-md shadow-md">
    <div class="p-4 flex gap-4 items-center">
      <%= link_to map_path, class: "inline-flex items-center gap-1 rounded-md bg-neutral-800 px-2 pr-2.5 py-1 text-xs text-neutral-50 ring-1 ring-neutral-200/10 ring-inset hover:bg-neutral-700 hover:ring-neutral-200/20" do %>
        <%= icon "arrow-long-left", variant: :micro, options: { class: "size-4"} %>
        Back
      <% end %>
      <h2 class="font-bold"><%= @recipe.name %></h2>
    </div>
    <%= render @recipe, location: @location, node: @node %>
  </div>
<% end %>