config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  mount SolidQueueDashboard::Engine, at: "/solid-queue"

  devise_for :users, path: "", path_names: { sign_up: "register", sign_in: "login", sign_out: "logout" }
  resources :users, only: [ :index, :show ]

  resources :characters do
    member do
      post :choose
    end
  end

  get "items", to: "items#index"

  root "home#show"

  get "map", to: "map#show"
  resources :locations, only: :show do
    resources :nodes, only: :show do
      resources :recipes, only: :show
    end
  end

  resources :messages, only: :create

  resources :guilds
  resources :guild_characters

  resource :equipment
  resources :actions
end

app/models/character.rb
class Character < ApplicationRecord
  # associations
  belongs_to :user, default: -> { Current.user }
  has_many :inventory_items, dependent: :destroy
  has_many :equipment_items, dependent: :destroy
  has_many :actions, dependent: :destroy
  has_one :guild_character, dependent: :destroy
  has_one :guild, through: :guild_character

  attribute :coins, default: 0

  # validations
  validates :name, presence: true, uniqueness: true, length: { in: 4..20 }, format: { with: /\A[a-zA-Z\d]+\z/, message: "only allows letters and numbers" }
  validates :coins, numericality: { greater_than_or_equal_to: 0 }
  validates :location_id, presence: true, inclusion: { in: Location.pluck(:id) }
  validates :race_id, presence: true, inclusion: { in: Race.pluck(:id) }

  before_create :set_starting_location

  def inventory
    Inventory.new(self)
  end

  delegate :equipped?, to: :equipment

  def equipment
    Equipment.new(self)
  end

  def location
    Location.find(location_id) if location_id.present?
  end

  def race
    Race.find(race_id) if race_id.present?
  end

  private

  def set_starting_location
    self.location_id = race.starting_location_id
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  skip_require_character! only: %i[ index new choose create ]
  before_action :set_character, only: %i[ show edit choose update destroy ]

  respond_to :turbo_stream, only: :update

  def index
    @characters = Character.all

    respond_with @characters
  end

  def show
    respond_with @character
  end

  def new
    @character = Character.new

    respond_with @character
  end

  def edit
    respond_with @character
  end

  def choose
    set_current_character @character.id
    respond_with @character, location: -> { root_url }
  end

  def create
    @character = Character.new(character_params)
    @character.save

    respond_with @character
  end

  def update
    @character.update(character_params)

    respond_with @character do |format|
      format.turbo_stream { flash.now[:notice] = "Character updated" }
    end
  end

  def destroy
    @character.destroy

    respond_with @character
  end

  private

  def set_character
    @character = Character.find(params.expect(:id))
  end

  def character_params
    params.expect(character: [ :name, :race_id, :location_id, :online ])
  end
end

app/views/characters/_character.html.erb
<%= turbo_frame_tag character do %>
  <div>
    <strong class="block font-medium mb-1">Name:</strong>
    <%= character.name %>... online: <%= character.online? %> (<%= button_to "switch", character, params: { character: { online: !character.online? } }, form_class: "inline-block", class: "cursor-pointer italic text-gray-600 dark:text-blue-500 hover:underline" %>) <%= link_to "characters", characters_path, class: "cursor-pointer italic text-gray-600 dark:text-blue-500 hover:underline", data: { turbo_frame: "_top" } %>
  </div>
<% end %>

app/views/characters/_form.html.erb
<%= form_with(model: character, class: "contents") do |form| %>
  <% if character.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul class="list-disc ml-6">
        <% character.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": character.errors[:name].none?, "border-red-400 focus:outline-red-600": character.errors[:name].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :race_id %>
    <%= form.collection_select :race_id, Race.all, :id, :name, prompt: true %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/characters/edit.html.erb
<% content_for :title, "Editing character" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing character</h1>

  <%= render "form", character: @character %>

  <%= link_to "Show this character", @character, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to characters", characters_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/characters/index.html.erb
<% content_for :title, "Characters" %>

<div class="flex justify-between items-center">
  <h1 class="font-bold text-4xl">Characters</h1>
  <%= link_to "New character", new_character_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
</div>

<% if @characters.any? %>
  <ul role="list" class="mt-4 divide-y divide-gray-100 overflow-hidden bg-white shadow-sm ring-1 ring-gray-900/5 sm:rounded-xl">
    <% @characters.each do |character| %>
      <li class="relative flex justify-between gap-x-6 px-4 py-5 hover:bg-gray-50 sm:px-6">
        <div class="flex min-w-0 gap-x-4">
          <div class="min-w-0 flex-auto">
            <p class="text-sm/6 font-semibold text-gray-900">
              <%= button_to [:choose, character], method: :post, class: "cursor-pointer" do %>
                <span>
                <span class="absolute inset-x-0 -top-px bottom-0"></span>
                <%= character.name %>
              <% end %>
            </p>
          </div>
        </div>
        <div class="flex shrink-0 items-center gap-x-4">
          <svg class="size-5 flex-none text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true" data-slot="icon">
            <path fill-rule="evenodd" d="M8.22 5.22a.75.75 0 0 1 1.06 0l4.25 4.25a.75.75 0 0 1 0 1.06l-4.25 4.25a.75.75 0 0 1-1.06-1.06L11.94 10 8.22 6.28a.75.75 0 0 1 0-1.06Z" clip-rule="evenodd" />
          </svg>
        </div>
      </li>
    <% end %>
  </ul>
<% else %>
  <p class="text-center my-10">No characters found.</p>
<% end %>

app/views/characters/new.html.erb
<% content_for :title, "New character" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New character</h1>

  <%= render "form", character: @character %>

  <%= link_to "Back to characters", characters_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/characters/show.html.erb
<% content_for :title, @character.name %>

<%= render @character %>

app/views/characters/update.turbo_stream.erb
<%= turbo_stream.prepend :flashes, partial: "layouts/flash" %>

<%= turbo_stream.replace(@character) { render @character } %>
<%= turbo_stream.replace(:map) { render("map/map", character: @character) } %>