config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  mount SolidQueueDashboard::Engine, at: "/solid-queue"

  devise_for :users, path: "", path_names: { sign_up: "register", sign_in: "login", sign_out: "logout" }
  resources :users, only: [ :index, :show ]

  resources :characters do
    member do
      post :choose
    end
  end

  get "items", to: "items#index"

  root "home#show"

  get "map", to: "map#show"
  resources :locations, only: :show do
    resources :nodes, only: :show do
      resources :recipes, only: :show
    end
  end

  resources :messages, only: :create

  resources :guilds
  resources :guild_characters

  resource :equipment
  resources :actions
end

app/controllers/map_controller.rb
class MapController < ApplicationController
  def show
  end
end

app/views/map/_map.html.erb
<% opened ||= false %>

<div class="divide-y divide-neutral-600">
  <details <%= if opened then "open" end %> class="bg-neutral-900 border-y md:border border-neutral-600 open:divide-y divide-neutral-600 overflow-hidden md:rounded-md shadow-md">
    <summary class="cursor-pointer select-none p-4 flex gap-2 items-center hover:bg-neutral-800">
      <%= image_tag("icons/map.png", height: 32, width: 32, class: "pixelized") %>
      <h2 class="font-bold">Map</h2>
    </summary>
    <section class="w-full relative flex justify-between gap-x-6 px-4 py-3.5 hover:bg-neutral-800">
      <% location = Location.find("vaelthorn") %>
      <div class="flex min-w-0 gap-x-4">
        <div class="min-w-0 flex-auto">
          <%= link_to location, data: { turbo_frame: "modal" } do %>
            <span class="absolute inset-x-0 -top-px bottom-0"></span>
            <span class="text-sm/6 font-semibold">
              <%= location.name %>
            </span>
          <% end %>
          <p class="mt flex text-xs/5 text-neutral-200">
            <%= location.type %>
          </p>
        </div>
      </div>
    </section>
    <div class="grid md:grid-cols-3 grow md:divide-x divide-neutral-600">
      <section class="divide-y divide-neutral-600">
        <div class="py-3.5 px-4 bg-neutral-950">
          <h2 class="font-semibold">Thul'Kaar</h2>
          <p class="text-sm text-neutral-100">Orc fortresses, villages and outskirts</p>
        </div>
        
        <ul role="list" class="divide-y divide-neutral-800 overflow-hidden bg-neutral-900 shadow-sm ring-1 ring-neutral-900/5">
          <% Location.where(race: "orc").each do |location| %>
            <li class="relative flex justify-between gap-x-6 px-4 py-3.5 hover:bg-neutral-800">
              <div class="flex min-w-0 gap-x-4">
                <div class="min-w-0 flex-auto">
                  <%= link_to location, data: { turbo_frame: "modal" } do %>
                    <span class="absolute inset-x-0 -top-px bottom-0"></span>
                    <span class="text-sm/6 font-semibold">
                      <%= location.name %>
                    </span>
                  <% end %>
                  <p class="mt flex text-xs/5 text-neutral-200">
                    <%= location.type %>
                  </p>
                </div>
              </div>
            </li>
          <% end %>
        </ul>
      </section>
      <section class="border-t md:border-t-0 border-neutral-600 divide-y divide-neutral-600">
        <div class="py-3.5 px-4 bg-neutral-950">
          <h2 class="font-semibold">Syl'Anora</h2>
          <p class="text-sm text-neutral-100">Elf fortresses, villages and outskirts</p>
        </div>
        
        <ul role="list" class="divide-y divide-neutral-800 overflow-hidden bg-neutral-900 shadow-sm ring-1 ring-neutral-900/5">
          <% Location.where(race: "elf").each do |location| %>
            <li class="relative flex justify-between gap-x-6 px-4 py-3.5 hover:bg-neutral-800">
              <div class="flex min-w-0 gap-x-4">
                <div class="min-w-0 flex-auto">
                  <%= link_to location, data: { turbo_frame: "modal" } do %>
                    <span class="absolute inset-x-0 -top-px bottom-0"></span>
                    <span class="text-sm/6 font-semibold">
                      <%= location.name %>
                    </span>
                  <% end %>
                  <p class="mt flex text-xs/5 text-neutral-200">
                    <%= location.type %>
                  </p>
                </div>
              </div>
            </li>
          <% end %>
        </ul>
      </section>
      <section class="border-t md:border-t-0 border-neutral-600 divide-y divide-neutral-600">
        <div class="py-3.5 px-4 bg-neutral-950">
          <h2 class="font-semibold">Aldorwyn</h2>
          <p class="text-sm text-neutral-100">Human fortresses, villages and outskirts</p>
        </div>
        
        <ul role="list" class="divide-y divide-neutral-800 overflow-hidden bg-neutral-900 shadow-sm ring-1 ring-neutral-900/5">
          <% Location.where(race: "human").each do |location| %>
            <li class="relative flex justify-between gap-x-6 px-4 py-3.5 hover:bg-neutral-800">
              <div class="flex min-w-0 gap-x-4">
                <div class="min-w-0 flex-auto">
                  <%= link_to location, data: { turbo_frame: "modal" } do %>
                    <span class="absolute inset-x-0 -top-px bottom-0"></span>
                    <span class="text-sm/6 font-semibold">
                      <%= location.name %>
                    </span>
                  <% end %>
                  <p class="mt flex text-xs/5 text-neutral-200">
                    <%= location.type %>
                  </p>
                </div>
              </div>
            </li>
          <% end %>
        </ul>
      </section>
    </div>
  </details>
</div>

app/views/map/_nodes.erb
<%= turbo_frame_tag :nodes do %>
  <% location = character.location %>
  <div class="divide-y divide-gray-200 overflow-hidden rounded-lg bg-white shadow">
    <div class="px-4 py-5 sm:px-6">
      <h2><%= location.name %></h2>
    </div>
    <div class="px-4 py-5 sm:p-6">
      <ul class="pl-4 list-disc list-inside">
        <% action = ActionManager.active_for(character) %>
        <% location.nodes.each do |node| %>
          <li>
            <% if action&.location == location && action&.node == node %>
              <strong><%= node.name %></strong>
            <% elsif node.recipes.any? %>
              <strong><%= node.name %></strong>
              <ul class="pl-4 list-disc list-inside">
                <% node.recipes.each do |recipe| %>
                  <li>
                    <%= button_to recipe.name, character_action_path(character), params: { node_id: node.id, recipe_id: recipe.id }, data: { turbo: false }, form_class: "inline-block", class: "cursor-pointer font-medium text-blue-600 dark:text-blue-500 hover:underline" %>
                  </li>
                <% end %>
              </ul>
            <% else %>
              <%= button_to node.name, character_action_path(character), params: { node_id: node.id }, data: { turbo: false }, form_class: "inline-block", class: "cursor-pointer font-medium text-blue-600 dark:text-blue-500 hover:underline" %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/map/_nodes.html.erb
<%= turbo_frame_tag :nodes do %>
  <% location = character.location %>
  <div class="divide-y divide-neutral-700 overflow-hidden rounded-lg bg-neutral-900 shadow">
    <div class="px-4 py-5 sm:px-6">
      <h2><%= location.name %></h2>
    </div>
    <div class="px-4 py-5 sm:p-6">
      <ul class="pl-4 list-disc list-inside">
        <% action = character.actions.active.first %>
        <% location.nodes.each do |node| %>
          <li>
            <% if action&.location == location && action&.node == node %>
              <strong><%= node.name %></strong>
            <% elsif node.recipes.any? %>
              <strong><%= node.name %></strong>
              <ul class="pl-4 list-disc list-inside">
                <% node.recipes.each do |recipe| %>
                  <li>
                    <%= button_to recipe.name, actions_path, params: { node_action: { location_id: location.id, node_id: node.id, recipe_id: recipe.id }}, data: { turbo: false }, form_class: "inline-block", class: "cursor-pointer font-medium text-blue-600 dark:text-blue-500 hover:underline" %>
                  </li>
                <% end %>
              </ul>
            <% else %>
              <%= button_to node.name, actions_path, params: { node_action: { location_id: location.id, node_id: node.id }}, data: { turbo: false }, form_class: "inline-block", class: "cursor-pointer font-medium text-blue-600 dark:text-blue-500 hover:underline" %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/map/show.html.erb
<%= render "map", opened: true  %>