config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  mount SolidQueueDashboard::Engine, at: "/solid-queue"

  devise_for :users, path: "", path_names: { sign_up: "register", sign_in: "login", sign_out: "logout" }
  resources :users, only: [ :index, :show ]

  resources :characters do
    member do
      post :choose
    end
  end

  get "items", to: "items#index"

  root "home#show"

  get "map", to: "map#show"
  resources :locations, only: :show do
    resources :nodes, only: :show do
      resources :recipes, only: :show
    end
  end

  resources :messages, only: :create

  resources :guilds
  resources :guild_characters

  resource :equipment
  resources :actions
end

app/models/guild_character.rb
class GuildCharacter < ApplicationRecord
  belongs_to :guild
  belongs_to :character

  validates :character, uniqueness: { scope: :guild }
end

app/controllers/guild_characters_controller.rb
class GuildCharactersController < ApplicationController
  before_action :set_guild_character, only: %i[ show edit update destroy ]

  # GET /guild_characters
  def index
    @guild_characters = GuildCharacter.all
  end

  # GET /guild_characters/1
  def show
  end

  # GET /guild_characters/new
  def new
    @guild_character = GuildCharacter.new
  end

  # GET /guild_characters/1/edit
  def edit
  end

  # POST /guild_characters
  def create
    @guild_character = GuildCharacter.new(guild_character_params)

    if @guild_character.save
      redirect_to @guild_character, notice: "Guild character was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /guild_characters/1
  def update
    if @guild_character.update(guild_character_params)
      redirect_to @guild_character, notice: "Guild character was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /guild_characters/1
  def destroy
    @guild_character.destroy!
    redirect_to guild_characters_path, notice: "Guild character was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guild_character
      @guild_character = GuildCharacter.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def guild_character_params
      params.expect(guild_character: [ :guild_id, :character_id, :role ])
    end
end

app/views/guild_characters/_form.html.erb
<%= form_with(model: guild_character, class: "contents") do |form| %>
  <% if guild_character.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(guild_character.errors.count, "error") %> prohibited this guild_character from being saved:</h2>

      <ul class="list-disc ml-6">
        <% guild_character.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :guild_id %>
    <%= form.text_field :guild_id, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": guild_character.errors[:guild_id].none?, "border-red-400 focus:outline-red-600": guild_character.errors[:guild_id].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :character_id %>
    <%= form.text_field :character_id, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": guild_character.errors[:character_id].none?, "border-red-400 focus:outline-red-600": guild_character.errors[:character_id].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :role %>
    <%= form.text_field :role, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": guild_character.errors[:role].none?, "border-red-400 focus:outline-red-600": guild_character.errors[:role].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/guild_characters/_guild_character.html.erb
<div id="<%= dom_id guild_character %>" class="my-5 space-y-5 flex gap-2">
  <div>
    <strong class="block font-medium mb-1">Character:</strong>
    <%= guild_character.character.name %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Role:</strong>
    <%= guild_character.role %>
  </div>
</div>

app/views/guild_characters/edit.html.erb
<% content_for :title, "Editing guild character" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing guild character</h1>

  <%= render "form", guild_character: @guild_character %>

  <%= link_to "Show this guild character", @guild_character, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to guild characters", guild_characters_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/guild_characters/index.html.erb
<% content_for :title, "Guild characters" %>

<div class="flex justify-between items-center">
  <h1 class="font-bold text-4xl">Guild characters</h1>
  <%= link_to "New guild character", new_guild_character_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
</div>

<div id="guild_characters" class="min-w-full divide-y divide-gray-200 space-y-5">
  <% if @guild_characters.any? %>
    <% @guild_characters.each do |guild_character| %>
      <div class="flex justify-between items-center">
        <%= render guild_character %>
        <div class="space-x-2">
          <%= link_to "Show", guild_character, class: "rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
          <%= link_to "Edit", edit_guild_character_path(guild_character), class: "rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
          <div class="inline-block">
            <%= button_to "Destroy", guild_character, method: :delete, class: "rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
          </div>
        </div>
      </div>
    <% end %>
  <% else %>
    <p class="text-center my-10">No guild characters found.</p>
  <% end %>
</div>

app/views/guild_characters/new.html.erb
<% content_for :title, "New guild character" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New guild character</h1>

  <%= render "form", guild_character: @guild_character %>

  <%= link_to "Back to guild characters", guild_characters_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/guild_characters/show.html.erb
<% content_for :title, "Showing guild character" %>

<h1 class="font-bold text-4xl">Showing guild character</h1>

<%= render @guild_character %>

<%= link_to "Edit this guild character", edit_guild_character_path(@guild_character), class: "mt-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
<%= link_to "Back to guild characters", guild_characters_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
<div class="inline-block ml-2">
  <%= button_to "Destroy this guild character", @guild_character, method: :delete, class: "mt-2 rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>